server:
  port: 3344

spring:
  application:
    name: cloud-config-center    #注册进eureka服务的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mingchengtianxia/springccloud-config.git
        ####搜索目录
          search-paths:
            - springccloud-config
      label: master

eureka:
   client:
     service-url:
       defaultZone: http://localhost:7001/eureka