server:
  port: 80

eureka:
  client:
    #true 表示向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版


#设置客户端超时时间（openFeign默认支持ribbon)
ribbon:
#建立连接所用时间
  ReadTimeout: 5000
  #值得是建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 5000

logging:
  level:
  # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
