server:
  port: 80

eureka:
  client:
    #true 表示向注册中心注册自己
    register-with-eureka: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: true